# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java Release with Gradle

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew jar
    - name: Set version
      id: version
      run: |
        REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
        VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
        echo ::set-output name=version::$VERSION
        echo ::set-output name=filename::$REPOSITORY-$VERSION
    - name: Create Release
      id: create_release
      uses: elgohr/Github-Release-Action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ github.event.pull_request.title }}
          release_name: $REPOSITORY-$VERSION
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
