# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java Release with Gradle

on:
  push:
    tags: 
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Jar with Gradle
      run: ./gradlew jar
      
    - name: Get the version
      id: get_version
      run: VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
      
    - name: Get the repo name
      id: get_repo
      run: REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")

    - name: Get commit summary
      id: get_commit_summary
      run: |
        PREVIOUS_TAG=$(git tag --sort=-creatordate | sed -n 2p)
        echo "PREVIOUS_TAG: $PREVIOUS_TAG"
        COMMIT_SUMMARY="$(git log --oneline --pretty=tformat:"%h %s" $PREVIOUS_TAG..${{ github.ref }})"
        COMMIT_SUMMARY="${COMMIT_SUMMARY//$'\n'/'%0A'}"
        echo ::set-output name=COMMIT_SUMMARY::$COMMIT_SUMMARY

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
            ${{ steps.get_commit_summary.outputs.COMMIT_SUMMARY }}
        draft: false
        prerelease: false
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
    # Artifact name
        name: ${{ steps.get_repo.outputs.REPOSITORY }}.${{ steps.get_version.outputs.VERSION}} # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
        path: build/libs/*.jar
